# Generated by Django 3.2.13 on 2022-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_auto_20220522_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_training',
            field=models.ManyToManyField(related_name='user', to='tgbot.Trening', verbose_name='Доступные тренировки'),
        ),
    ]
